name: CD - Deploy UpdateKeyFunc function

on:
  push:
    branches: ["main"]
    paths:
        - ".github/workflows/deploy-updatekeyfunc.yml"
        - "functions/updateKeyFunc/**"
        - "functions/lib/**"

jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        node: [ 16.x, 18.x, 20.x ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm run test

  deploy:
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - uses: actions/checkout@v3

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APP_CREDENTIALS_BASE64 }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
           project_id: '${{ secrets.GOOGLE_PROJECT_ID }}'

      - name: Deploy cloud functions
        run: gcloud functions deploy UpdateKeyFunc --project ${{ secrets.GOOGLE_PROJECT_ID }} --no-allow-unauthenticated --region=southamerica-east1 --trigger-http --runtime=nodejs18 --update-labels=module=signatures --source=.
