name: CD - Dockerhub

on:
  push:
    branches: 
      - "release/**"
      - "main"
    paths:
        - ".github/workflows/deploy-docker-images.yml"
        - "functions/createKeyFunc/**"
        - "functions/updateKeyFunc/**"
        - "functions/lib/**"

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: git-clone
        name: Cloning repository

      - uses: dorny/paths-filter@v3
        id: path-filter
        with:
          base: ${{ github.ref }}
          filters: |
            workflow:
              - ".github/workflows/deploy-functions.yml"
            createfunc:
              - "functions/createKeyFunc/**"
            updatefunc:
              - "functions/updateKeyFunc/**"
            lib:
              - "functions/lib/**"

      - name: Docker hub login
        id: docker-hub-login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - uses: docker/build-push-action@v2
        name: Build and push image
        id: build-and-push
        if: |
          steps.path-filter.outputs.createfunc == 'true' ||
          steps.path-filter.outputs.updatefunc == 'true' || 
          steps.path-filter.outputs.lib == 'true' || 
          steps.path-filter.outputs.workflow == 'true'
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_IMAGE_TAG}} 

