name: CD - Deploy on Docker Hub

on:
  workflow_run:
    workflows:
      - CD - Deploy functions
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: git-clone
        name: Cloning repository

      - uses: dorny/paths-filter@v3
        id: path-filter
        with:
          base: ${{ github.ref }}
          filters: |
            workflow:
              - ".github/workflows/deploy-functions.yml"
            docker:
              - ".github/workflows/docker-for-dev-env.yml"
            createfunc:
              - "functions/createKeyFunc/**"
            updatefunc:
              - "functions/updateKeyFunc/**"
            lib:
              - "functions/lib/**"

      - uses: docker/login-action@v1
        id: docker-hub-login
        name: Docker hub login
        if: |
          steps.path-filter.outputs.createfunc == 'true' || 
          steps.path-filter.outputs.lib == 'true' || 
          steps.path-filter.outputs.workflow == 'true' ||
          steps.path-filter.outputs.docker == 'true'
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - uses: docker/build-push-action@v2
        name: Build and push image
        id: build-and-push
        if: |
          steps.path-filter.outputs.createfunc == 'true' || 
          steps.path-filter.outputs.lib == 'true' || 
          steps.path-filter.outputs.workflow == 'true' ||
          steps.path-filter.outputs.docker == 'true'
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_IMAGE_TAG}} 

