name: CI - Eslint

on: 
  workflow_run:
    workflows: [CI - Unit Tests]
    types: 
      - requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        id: git-clone
        name: Cloning repository

      - uses: pnpm/action-setup@v2
        id: install-pnpm
        name: Installing PNPM
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        id: set-nodejs
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Insltall dependencies
        id: set-deps
        run: pnpm install --frozen-lockfile

      - name: Run Eslint
        id: eslint
        run: pnpm run lint
